version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"

    # Override env vars here:
    environment:
      - NODE_ENV=${NODE_ENV}
      - HOSTNAME=${HOSTNAME}
      - PORT=${PORT}
